FROM node:alpine

RUN addgroup app && adduser -S -G app app
RUN mkdir /usr/app && chown app:app /usr/app
USER app

WORKDIR '/usr/app'

COPY package.json .
RUN npm install

COPY . .
CMD ["npm", "run", "start"]